baseurl = "https://newprojectionspodcast.com/"
languageCode = "en-us"
title = "New Projections"
theme = "castanet"
googleAnalytics = ""
# themesdir = "../.."
paginate = "9"
buildFuture = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[permalinks]
	# page = "/:filename/"
	# about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
# [[Menu.Main]]
#     name = "About"
#     identifier = "about"
#     url = "/about"

[[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "/contact"


# [[Menu.Main]]
#     name = "Blog"
#     identifier = "blog"
#     url = "/blog"

[params]
favicon = "img/favicon.ico"
googleAnalytics_UA = ""
mainSections = ["episode"]
episode_number_style  = "brackets"
# episode_number_prefix = "CWC"
site_theme = "grey"
# site_layout = "grid"
site_layout = "row"
show_next_upcoming = "false"
enable_jumbo = "true"
# enable_jumbo = "false"
disable_title_caps = "true"
# truncate = "100"
# about_logo = "/img/hugocast.png"
copyright_notice = "Copyright 2024 [Curtis Bird](https://oldmapgallery.com/)"
# youtube_subscribe = "https://www.youtube.com/@theoldmapgallery4158?sub_confirmation=1"
itunes_subscribe = "https://podcasts.apple.com/us/podcast/new-projections/id1412580312?ign-mpt=uo%3D4&mt=2"
google_play_subscribe = "https://podcasts.google.com/feed/aHR0cHM6Ly9mZWVkcy5zb3VuZGNsb3VkLmNvbS91c2Vycy9zb3VuZGNsb3VkOnVzZXJzOjM3OTM2ODE3My9zb3VuZHMucnNz"
soundcloud_subscribe = "http://feeds.soundcloud.com/users/soundcloud:users:203144248/sounds.rss"
# rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "From an interest in the people that create maps and data visualizations, comes this series of conversations discussing history, change and the potential of future. An ongoing discussion of the frontiers of discovery and understanding."
media_prefix = "https://newprojectionspodcast.com/" # CHANGE TO LOCALHOST FOR LOCAL DEVELOPMENT
disqusShortname = ""
  [params.feed]
    copyright = "Copyright 2024 Curtis Bird" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Podcast by Curtis Bird" #no markdown or HTML
    itunes_author = "Curtis Bird" #no markdown or HTML
    itunes_summary = "From an interest in the people that create maps and data visualizations, comes this series of conversations discussing history, change and the potential of future. An ongoing discussion of the frontiers of discovery and understanding." # TOTO -  Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Curtis Bird"
    itunes_owner_email = "newprojectionscast@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on Apple Podcasts. It will not be publicly displayed on Apple Podcasts.
    itunes_image = "https://newprojectionspodcast.com/img/logo.png"
    itunes_top_category = "Education"
    itunes_first_sub_category = "Technology"
    # itunes_second_sub_category = "Cartography"
    language = "en-us"

  # Social links can be given in full URL form or short form
  # In the short form the theme will generate a relevant URL
  [params.social]
    youtube = "@theoldmapgallery4158"
    # Short form in linkedin will link to a user's page so use long form for company pages
    mastodon = "https://sciencemastodon.com/@oldmapgallery"